### ISSUE TITLE
Cannot connect bme680 sensor to Cayenne 

### ISSUE THREAD

**Issue by PrzemekSkw** [myDevicesIoT/Cayenne-MQTT-Python#14]
Hi, I'm new to Cayenne and I'm not programmer. Can somebody explain me how to connect my bme680 sensor connected to raspberry pi zero to Cayenne dashboard. I open dashboard Add new device, click Bring Your own Thing, I add that to my file read-all.py [i run that file in raspbian command line to show measurements from sensor]:
```
import time
import cayenne.client
import bme680

# Cayenne authentication info. This should be obtained from the Cayenne Dashboard.
MQTT_USERNAME  = "mqqt_user_from_page"
MQTT_PASSWORD  = "mqqt_pass_from_page"
MQTT_CLIENT_ID = "mqqt_id_from_page"
```
and fill with credentials from website dashboard. When I run python read-cayenne.py I see that is connecting to `mqtt.mydevices.com:1883` and show measurements in console but when I go to dashboard I see that is offline:
![Zrzut ekranu z 2019-12-02 22-23-35](https://user-images.githubusercontent.com/25219988/69996504-7e60dc00-1552-11ea-82aa-f465fb837d2e.png)

Regards,
Przemek

**Comment by jburhenn** [comment]
Hi, welcome to Cayenne. This question is probably better asked in the Cayenne Community since this page is for bugs with the library itself, while it looks like the issue you are seeing is probably a UI issue with the site. Please try posting your issue as a new topic at https://community.mydevices.com. Thanks.
